# Generated by Django 2.1.5 on 2019-01-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190123_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='aliases',
        ),
        migrations.AddField(
            model_name='alias',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='Account'),
            preserve_default=False,
        ),
    ]
