# Generated by Django 2.1.5 on 2019-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='def_pwd',
            field=models.CharField(default='', max_length=50, verbose_name='default password'),
            preserve_default=False,
        ),
    ]
