# Generated by Django 2.1.5 on 2019-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190123_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, max_length=250, upload_to='uploads/', verbose_name='Logo'),
        ),
    ]
