# Generated by Django 2.1.5 on 2019-01-23 18:10

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Logo'),
        ),
    ]
