# Generated by Django 2.1.5 on 2019-01-24 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_alias_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
