# Generated by Django 2.1.5 on 2019-01-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_tenant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='imap_port',
            field=models.CharField(default='143', max_length=3, verbose_name='IMAP server port'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='imap_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('STL', 'STARTTLS')], default='NNE', max_length=3, verbose_name='IMAP server security'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='imap_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IMAP server address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_port',
            field=models.CharField(default='25', max_length=3, verbose_name='SMTP server port'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('STL', 'STARTTLS')], default='NNE', max_length=3, verbose_name='SMTP server security'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SMTP server address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='weburl',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
