# Generated by Django 2.1.5 on 2019-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190124_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='account user'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.EmailField(max_length=254, unique=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='imap_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('STL', 'SSL/TLS'), ('STL', 'STARTTLS')], default='NNE', max_length=3, verbose_name='IMAP connection security'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='smtp_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('STL', 'SSL/TLS'), ('STL', 'STARTTLS')], default='NNE', max_length=3, verbose_name='SMTP connection security'),
        ),
    ]
