# Generated by Django 2.1.5 on 2019-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190129_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirection',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
