# Generated by Django 4.0.2 on 2022-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200327_1523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('mail', 'mail account'), ('othr', 'Passwort')], default='mail', max_length=4, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('1', 'account'), ('2', 'alias'), ('3', 'password')], default='1', max_length=1, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='account user'),
        ),
    ]
