# Generated by Django 4.0.2 on 2022-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_account_date_alter_account_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
