# Generated by Django 4.0.2 on 2022-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN'),
        ),
    ]
