# Generated by Django 4.0.3 on 2022-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_account_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
