# Generated by Django 2.1.5 on 2019-01-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('account_usr', models.EmailField(max_length=254, verbose_name='account user')),
                ('def_pwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='default password')),
            ],
            options={
                'verbose_name': 'mail account',
                'verbose_name_plural': 'mail accounts',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('domain', models.CharField(blank=True, max_length=50, null=True, verbose_name='domain')),
            ],
            options={
                'verbose_name': 'mail tenant',
                'verbose_name_plural': 'mail tenants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailuser.Tenant', verbose_name='tenant'),
        ),
    ]
