# Generated by Django 2.1.5 on 2019-01-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_usr',
            new_name='username',
        ),
    ]
