# Generated by Django 2.1.5 on 2019-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0002_auto_20190123_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254, verbose_name='alias')),
            ],
            options={
                'verbose_name': 'mail alias',
                'verbose_name_plural': 'mail aliases',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='aliases',
            field=models.ManyToManyField(to='mailuser.Alias', verbose_name='Aliases'),
        ),
    ]
