# Generated by Django 2.1.5 on 2019-01-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0008_auto_20190123_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='description'),
        ),
    ]
