# Generated by Django 2.1.5 on 2019-01-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0017_auto_20190129_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='def_pwd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='default password'),
        ),
    ]
