# Generated by Django 2.1.5 on 2019-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0019_auto_20190129_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('1', 'account'), ('2', 'redirection')], default='1', max_length=1, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=254, verbose_name='account user'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('type', 'username')},
        ),
    ]
