# Generated by Django 3.0.4 on 2020-03-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailuser', '0021_auto_20190131_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('1', 'account'), ('2', 'alias')], default='1', max_length=1, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='imap_port',
            field=models.CharField(default='993', max_length=3, verbose_name='IMAP server port'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='imap_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('SST', 'SSL/TLS'), ('STS', 'STARTTLS')], default='SST', max_length=3, verbose_name='IMAP connection security'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='smtp_port',
            field=models.CharField(default='465', max_length=3, verbose_name='SMTP server port'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='smtp_sec',
            field=models.CharField(choices=[('NNE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS'), ('SST', 'SSL/TLS'), ('STS', 'STARTTLS')], default='SST', max_length=3, verbose_name='SMTP connection security'),
        ),
    ]
